private
programNames
	" Answer a list of program names for resolving their path to execute them "
	
	^ #('blast_formatter.exe'      
'blastdb_aliastool.exe'    
'blastdbcheck.exe'        
'blastdbcmd.exe'           
'blastn.exe'               
'blastp.exe'               
'blastx.exe'
'convert2blastmask.exe'    
'dustmasker.exe'           
'makeblastdb.exe'          
'makembindex.exe'          
'psiblast.exe'             
'rpsblast.exe'             
'rpstblastn.exe'           
'segmasker.exe'            
'tblastn.exe'              
'tblastx.exe'        
'windowmasker.exe') 