private
isExecCygwin
	" phmmer.exe reports 
	
	cygwin warning:
  MS-DOS style path detected: C:\MySmalltalkProjects\BioSmalltalk\BioSmalltalkTestFiles\globins4.sto
  Preferred POSIX equivalent is: /cygdrive/c/MySmalltalkProjects/BioSmalltalk/BioSmalltalkTestFiles/globins4.sto
  CYGWIN environment variable option 'nodosfilewarning' turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames"

	^ true