initialize-release
initializeThreeLetterAminoacidNames
	<lint: 'Method selectors' rationale: 'No spelling error' author: 'hfm'>

	^ Dictionary new
                at: 'ALA' put: 'Alanine';
                at: 'ARG' put: 'Arginine';
                at: 'ASN' put: 'Asparagine';
                at: 'ASP' put: 'Aspartic Acid';
                at: 'CYS' put: 'Cysteine';
                at: 'GLU' put: 'Glutamic Acid';
                at: 'GLN' put: 'Glutamine';
                at: 'GLY' put: 'Glycine';
                at: 'HIS' put: 'Histidine';
                at: 'ILE' put: 'Isoleucine';
                at: 'LEU' put: 'Leucine';
                at: 'LYS' put: 'Lysine';
                at: 'MET' put: 'Methionine';
                at: 'PHE' put: 'Phenylalanine';
                at: 'PRO' put: 'Proline';
                at: 'SER' put: 'Serine';
                at: 'THR' put: 'Threonine';
                at: 'TRP' put: 'Tryptophan';
                at: 'TYR' put: 'Tyrosine';
                at: 'VAL' put: 'Valine';
			yourself	