accessing - qualifiers
qualifierForTitleWord
	" Answer a <String> qualifier. Includes only those words found in the definition line of a record. The definition line summarizes the biology of the sequence and is carefully constructed by database staff. A standard definition line will include the organism, product name, gene symbol, molecule type and whether it is a partial or complete cds. Title Word indexes are not available in the Structure or PopSet databases. "

	^ '[TITL]'