report
geneAnnotNames

	^ #(
	'ENS-Locus_1' 'Orientation_1' 'Pos_11' 'UniGene-Cluster_1' 'Gene_1' 'Pos_21' 'Gene-Function_1'
	'ENS-Locus_2' 'Orientation_2' 'Pos_21' 'UniGene-Cluster_2' 'Gene_2' 'Pos_22' 'Gene-Function_2'
	'ENS-Locus_3' 'Orientation_3' 'Pos_31' 'UniGene-Cluster_3' 'Gene_3' 'Pos_23' 'Gene-Function_3'
	'ENS-Locus_4' 'Orientation_4' 'Pos_41' 'UniGene-Cluster_4' 'Gene_4' 'Pos_24' 'Gene-Function_4'	
	'ENS-Locus_5' 'Orientation_5' 'Pos_51' 'UniGene-Cluster_5' 'Gene_5' 'Pos_25' 'Gene-Function_5'
	'ENS-Locus_6' 'Orientation_6' 'Pos_61' 'UniGene-Cluster_6' 'Gene_6' 'Pos_26' 'Gene-Function_6'
	'ENS-Locus_7' 'Orientation_7' 'Pos_71' 'UniGene-Cluster_7' 'Gene_7' 'Pos_27' 'Gene-Function_7'	
	'ENS-Locus_8' 'Orientation_8' 'Pos_81' 'UniGene-Cluster_8' 'Gene_8' 'Pos_28' 'Gene-Function_8'
	'ENS-Locus_9' 'Orientation_9' 'Pos_91' 'UniGene-Cluster_9' 'Gene_9' 'Pos_29' 'Gene-Function_9'
	'ENS-Locus_10' 'Orientation_10' 'Pos_101' 'UniGene-Cluster_10' 'Gene_10' 'Pos_102' 'Gene-Function_10'	
	'ENS-Locus_11' 'Orientation_11' 'Pos_111' 'UniGene-Cluster_11' 'Gene_11' 'Pos_112' 'Gene-Function_11'
	'ENS-Locus_12' 'Orientation_12' 'Pos_121' 'UniGene-Cluster_12' 'Gene_12' 'Pos_122' 'Gene-Function_12'

	'NM-Locus_1' 'Orientation_1' 'Pos_11' 'UniGene-Cluster_1' 'Gene_1' 'Pos_21' 'Gene-Function_1'
	'NM-Locus_2' 'Orientation_2' 'Pos_21' 'UniGene-Cluster_2' 'Gene_2' 'Pos_22' 'Gene-Function_2'
	'NM-Locus_3' 'Orientation_3' 'Pos_31' 'UniGene-Cluster_3' 'Gene_3' 'Pos_23' 'Gene-Function_3'
	'NM-Locus_4' 'Orientation_4' 'Pos_41' 'UniGene-Cluster_4' 'Gene_4' 'Pos_24' 'Gene-Function_4'
	'NM-Locus_5' 'Orientation_5' 'Pos_51' 'UniGene-Cluster_5' 'Gene_5' 'Pos_25' 'Gene-Function_5'
	'NM-Locus_6' 'Orientation_6' 'Pos_61' 'UniGene-Cluster_6' 'Gene_5' 'Pos_26' 'Gene-Function_6'
	'NM-Locus_7' 'Orientation_7' 'Pos_71' 'UniGene-Cluster_7' 'Gene_7' 'Pos_27' 'Gene-Function_7'	
	'NM-Locus_8' 'Orientation_8' 'Pos_81' 'UniGene-Cluster_8' 'Gene_8' 'Pos_28' 'Gene-Function_8'
	'NM-Locus_9' 'Orientation_9' 'Pos_91' 'UniGene-Cluster_9' 'Gene_9' 'Pos_29' 'Gene-Function_9'
	'NM-Locus_10' 'Orientation_10' 'Pos_101' 'UniGene-Cluster_10' 'Gene_10' 'Pos_102' 'Gene-Function_10'	
	'NM-Locus_11' 'Orientation_11' 'Pos_111' 'UniGene-Cluster_11' 'Gene_11' 'Pos_112' 'Gene-Function_11'
	'NM-Locus_12' 'Orientation_12' 'Pos_121' 'UniGene-Cluster_12' 'Gene_12' 'Pos_122' 'Gene-Function_12'	
	)