tables
scenedesmusObliquusMitochondrialTable
	
	^ self tableClass new
add: 'TTT'-> 'F'; add: 'TTC'-> 'F'; add: 'TTA'-> 'L'; add: 'TTG'-> 'L'; add: 'TCT'-> 'S'; add:
'TCC'-> 'S'; add: 'TCG'-> 'S'; add: 'TAT'-> 'Y'; add: 'TAC'-> 'Y'; add: 'TAG'-> 'L'; add:
'TGT'-> 'C'; add: 'TGC'-> 'C'; add: 'TGG'-> 'W'; add: 'CTT'-> 'L'; add: 'CTC'-> 'L'; add:
'CTA'-> 'L'; add: 'CTG'-> 'L'; add: 'CCT'-> 'P'; add: 'CCC'-> 'P'; add: 'CCA'-> 'P'; add:
'CCG'-> 'P'; add: 'CAT'-> 'H'; add: 'CAC'-> 'H'; add: 'CAA'-> 'Q'; add: 'CAG'-> 'Q'; add:
'CGT'-> 'R'; add: 'CGC'-> 'R'; add: 'CGA'-> 'R'; add: 'CGG'-> 'R'; add: 'ATT'-> 'I'; add:
'ATC'-> 'I'; add: 'ATA'-> 'I'; add: 'ATG'-> 'M'; add: 'ACT'-> 'T'; add: 'ACC'-> 'T'; add:
'ACA'-> 'T'; add: 'ACG'-> 'T'; add: 'AAT'-> 'N'; add: 'AAC'-> 'N'; add: 'AAA'-> 'K'; add:
'AAG'-> 'K'; add: 'AGT'-> 'S'; add: 'AGC'-> 'S'; add: 'AGA'-> 'R'; add: 'AGG'-> 'R'; add:
'GTT'-> 'V'; add: 'GTC'-> 'V'; add: 'GTA'-> 'V'; add: 'GTG'-> 'V'; add: 'GCT'-> 'A'; add:
'GCC'-> 'A'; add: 'GCA'-> 'A'; add: 'GCG'-> 'A'; add: 'GAT'-> 'D'; add: 'GAC'-> 'D'; add:
'GAA'-> 'E'; add: 'GAG'-> 'E'; add: 'GGT'-> 'G'; add: 'GGC'-> 'G'; add: 'GGA'-> 'G'; add:
'GGG'-> 'G'; yourself