"
A BioOrthoScoreableTest is a test class for testing the behavior of BioOrthoScoreable
"
Class {
	#name : #BioOrthoScoreableTest,
	#superclass : #TestCase,
	#category : 'BioOrthoXML-Tests'
}

{ #category : #'tests-accessing' }
BioOrthoScoreableTest >> testAddScoreDefinitionScore [
]

{ #category : #'tests-accessing' }
BioOrthoScoreableTest >> testDefinedScores [
]

{ #category : #'tests-accessing' }
BioOrthoScoreableTest >> testScores [
]
