"
Allows to assign scores to subclasses. 
"
Class {
	#name : #BioOrthoScoreable,
	#superclass : #Object,
	#category : 'BioOrthoXML-Core'
}

{ #category : #accessing }
BioOrthoScoreable >> addScoreDefinition: aBioOrthoScoreDefinition score: anInteger [
	" Adds a score for with given type."
]

{ #category : #accessing }
BioOrthoScoreable >> definedScores [
	" Answer all the receiver's defined scores "
]

{ #category : #accessing }
BioOrthoScoreable >> scores [
	" Answer all the receiver's scores "
]
