"
Represent the definition of a score. A score is defined by an identifier and a description. Scores can can assigned to groups in context of the membership to a certain group. 
"
Class {
	#name : #BioOrthoScoreDefinition,
	#superclass : #Object,
	#category : 'BioOrthoXML-Core'
}

{ #category : #comparing }
BioOrthoScoreDefinition >> = aBioOrthoScoreDefinition [

]

{ #category : #comparing }
BioOrthoScoreDefinition >> description [
	" Answer a <String> with the score description. "
]

{ #category : #private }
BioOrthoScoreDefinition >> hash [

]

{ #category : #comparing }
BioOrthoScoreDefinition >> id [
	" Answer a <String> with the score identifier."
]
