"
A BioOrthoGeneTest is a test class for testing the behavior of BioOrthoGene
"
Class {
	#name : #BioOrthoGeneTest,
	#superclass : #TestCase,
	#category : 'BioOrthoXML-Tests'
}

{ #category : #'tests-accessing' }
BioOrthoGeneTest >> testDatabase [
]

{ #category : #'tests-accessing' }
BioOrthoGeneTest >> testGeneIdentifier [
]

{ #category : #'tests-private' }
BioOrthoGeneTest >> testHash [
]

{ #category : #'tests-accessing' }
BioOrthoGeneTest >> testProteinIdentifier [
]

{ #category : #'tests-accessing' }
BioOrthoGeneTest >> testSpecies [
]

{ #category : #'tests-accessing' }
BioOrthoGeneTest >> testTranscriptIdentifier [
]
