"
Represents a species in the context of orthology assignment. 

"
Class {
	#name : #BioOrthoSpecies,
	#superclass : #Object,
	#category : 'BioOrthoXML-Core'
}

{ #category : #comparing }
BioOrthoSpecies >> = aBioOrthoSpecies [

]

{ #category : #private }
BioOrthoSpecies >> hash [

]

{ #category : #accessing }
BioOrthoSpecies >> ncbiTaxId [
	"  Returns the NCBI taxonomy identifier of the species "
]
