SystemOrganization addCategory: #'BioTools-Adapters'!
SystemOrganization addCategory: #'BioTools-Alphabets'!
SystemOrganization addCategory: #'BioTools-Biological'!
SystemOrganization addCategory: #'BioTools-Collections'!
SystemOrganization addCategory: #'BioTools-Core'!
SystemOrganization addCategory: #'BioTools-IO'!
SystemOrganization addCategory: #'BioTools-Query'!
SystemOrganization addCategory: #'BioTools-Exceptions'!
