samples
hierarchyForClassesInCategoriesMatching: symbol

	"GraphViz hierarchyForClassesInCategoriesMatching: 'GraphViz'"
	"GraphViz hierarchyForClassesInCategoriesMatching: 'System-Archives'"
	"GraphViz hierarchyForClassesInCategoriesMatching: 'Collections-Weak'"
	"GraphViz hierarchyForClassesInCategoriesMatching: #DynamicBindings"			

	(SystemOrganization graphForCategoriesMatching: symbol) openInWindow