output types
outputFormats
	"All the output formats listed in GraphViz documentation (as of dot version 2.2)."

	^ #(
		#canon
		#cmap	"Client-side imagemap"
		#dot	"DOT"
		#fig	"FIG"
		#gd
		#gd2	"GD/GD2 formats"
		#gif	"GIF"
		#hpgl	"HP-GL/2"
		#imap	"Server-side imagemap"
		#ismap	"Server-side imagemap (deprecated)"
		#jpg
		#jpeg	"JPEG"
		#mif	"FrameMaker MIF format"
		#mp	"MetaPost"
		#pcl	"PCL"
		#pic	"PIC"
		#plain
		#'plain-ext'	"Simple text format"
		#png	"Portable Network Graphics format"
		#ps 	"PostScript"
		#ps2	"PostScript for PDF"
		#svg
		#svgz	"Scalable Vector Graphics"
		#vrml	"VRML"
		#vtx	"Visual Thought format"
		#wbmp	"Wireless BitMap format")