initialize - release
initializeClassifications
	" Private - Add software items to the receiver's catalog "

	" Answer a <Collection> of qualifiers to be used for classifying software items. Tags were taken from the following sites:
http://biowulf.nih.gov/apps/
http://www.ccmb.med.umich.edu/bioinf-core/tools	
http://bioinformatics.ca/links_directory/
	"
	^ 'Linkage
Pathway
Phylogenetics
Genome Browser
Comparative Analysis
NGS Aligners
Assembly
Microarray
Protein
Localization and Targeting
Annotation
Sequence Analysis
Gene Expression
Functional RNA
Programming Library
'

	