private
softwareListClassifiers
	" Answer a <Collection> of qualifiers to be used for classifying software items. Tags were taken from the following sites:
http://biowulf.nih.gov/apps/
http://www.ccmb.med.umich.edu/bioinf-core/tools	
http://bioinformatics.ca/links_directory/
	"
	^ 'Linkage
Pathway
Phylogenetics
Genome Browser
Comparative Analysis
NGS (Next-Generation Sequencing) read alignment
Assembly
Microarray
Protein
Localization and Targeting
Annotation
Sequence Analysis
Gene Expression
Functional RNA'
