accessing
nodeNames
	" Answer a <Collection> of all nodes used for structuring the blast tree "

	^ #('Hsp' 'Hit_hsps' 'Hit' 'BlastOutput_param' 'Parameters' 'Iteration' 'Iteration_hits' 'Iteration' 'BlastOutput_iterations' 'BlastOutput' 'Iteration_stat' 'Statistics' 'BlastOutput_program' 'BlastOutput_version' 'BlastOutput_reference' 'BlastOutput_db' 'BlastOutput_query-ID' 'BlastOutput_query-def' 'BlastOutput_query-len' )