tables
invertebrateMitocondrialTable
	<lint: 'Sends add:/remove: to external collection' rationale: 'No external collection' author: 'hfm'>
	<lint: 'Method selectors' rationale: 'No spelling error' author: 'hfm'>

	^ self tableClass new
add: 'UUU'-> 'F'; add: 'UUC'-> 'F'; add: 'UUA'-> 'L'; add: 'UUG'-> 'L'; add: 'UCU'-> 'S'; add:
'UCC'-> 'S'; add: 'UCA'-> 'S'; add: 'UCG'-> 'S'; add: 'UAU'-> 'Y'; add: 'UAC'-> 'Y'; add:
'UGU'-> 'C'; add: 'UGC'-> 'C'; add: 'UGA'-> 'W'; add: 'UGG'-> 'W'; add: 'CUU'-> 'L'; add:
'CUC'-> 'L'; add: 'CUA'-> 'L'; add: 'CUG'-> 'L'; add: 'CCU'-> 'P'; add: 'CCC'-> 'P'; add:
'CCA'-> 'P'; add: 'CCG'-> 'P'; add: 'CAU'-> 'H'; add: 'CAC'-> 'H'; add: 'CAA'-> 'Q'; add:
'CAG'-> 'Q'; add: 'CGU'-> 'R'; add: 'CGC'-> 'R'; add: 'CGA'-> 'R'; add: 'CGG'-> 'R'; add:
'AUU'-> 'I'; add: 'AUC'-> 'I'; add: 'AUA'-> 'M'; add: 'AUG'-> 'M'; add: 'ACU'-> 'T'; add:
'ACC'-> 'T'; add: 'ACA'-> 'T'; add: 'ACG'-> 'T'; add: 'AAU'-> 'N'; add: 'AAC'-> 'N'; add:
'AAA'-> 'K'; add: 'AAG'-> 'K'; add: 'AGU'-> 'S'; add: 'AGC'-> 'S'; add: 'AGA'-> 'S'; add:
'AGG'-> 'S'; add: 'GUU'-> 'V'; add: 'GUC'-> 'V'; add: 'GUA'-> 'V'; add: 'GUG'-> 'V'; add:
'GCU'-> 'A'; add: 'GCC'-> 'A'; add: 'GCA'-> 'A'; add: 'GCG'-> 'A'; add: 'GAU'-> 'D'; add:
'GAC'-> 'D'; add: 'GAA'-> 'E'; add: 'GAG'-> 'E'; add: 'GGU'-> 'G'; add: 'GGC'-> 'G'; add:
'GGA'-> 'G'; add: 'GGG'-> 'G'; yourself.