private
faoSpecies
	" Answer a <Collection> of FAO species in english language "

	^ #('Ass' 'Bactrian Camel' 'Buffalo' 'Cassowary' 'Cattle' 'Chicken' 'Chilean Tinamou' 'Deer' 'Dog' 'Dromedary' 'Dromedary/Bactrian Camel' 'Duck' 'Duck(domestic)/Muscovy duck' 'Emu' 'Goat' 'Goose' 'Guanaco' 'Guinea fowl' 'Guinea Pig' 'Horse' 'Llama' 'Muscovy duck' 'Nandu' 'Ostrich' 'Partridge' 'Peacock' 'Pheasant' 'Pig' 'Pigeon' 'Quail' 'Rabbit' 'Sheep' 'Swallow' 'Turkey' 'Vicuña' 'Yak').