accessing - dog
markerAlleleRangesForDog

	^ #(
		"Multiplex 1"	
		#('AHT121' 0 0)
		#('AHT171' 0 0)
		#('AHT253' 0 0)
		#('C22.279' 0 0)
		#('FH2001' 0 0)
		#('FH2054' 0 0)
		#('FH2164' 0 0)
		#('FH2611' 0 0)
		#('FH2247' 0 0)
		#('FH2289' 0 0)
		#('INRA21' 0 0)
		#('PEZO8' 0 0)

		"Multiplex 2"
		#('AHTk211' 0 0)
		#('LEI2D2' 0 0)
		#('FH2326' 0 0)
		#('FH2328' 0 0)
		#('FH2361' 0 0)
		#('PEZ12' 0 0)
		#('PEZ22' 0 0)
		#('FH2305' 0 0)
		#('PEZ03' 0 0)
		#('PEZ10' 0 0)
		#('PEZ11' 0 0)
		)
		
