accessing
gbSet02
	" GBSeq size = 2 "

	^ '<?xml version="1.0"?>
 <!DOCTYPE GBSet PUBLIC "-//NCBI//NCBI GBSeq/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_GBSeq.dtd">
<GBSeq>
  <GBSeq_locus>FJ815864</GBSeq_locus>
  <GBSeq_length>906</GBSeq_length>
  <GBSeq_strandedness>double</GBSeq_strandedness>
  <GBSeq_moltype>DNA</GBSeq_moltype>
  <GBSeq_topology>linear</GBSeq_topology>
  <GBSeq_division>MAM</GBSeq_division>
  <GBSeq_update-date>12-MAR-2010</GBSeq_update-date>
  <GBSeq_create-date>24-AUG-2009</GBSeq_create-date>
  <GBSeq_definition>Bos taurus isolate FRI9133 D-loop, partial sequence; mitochondrial</GBSeq_definition>
  <GBSeq_primary-accession>FJ815864</GBSeq_primary-accession>
  <GBSeq_accession-version>FJ815864.1</GBSeq_accession-version>
  <GBSeq_other-seqids>
    <GBSeqid>gb|FJ815864.1|</GBSeqid>
    <GBSeqid>gi|256041608</GBSeqid>
  </GBSeq_other-seqids>
  <GBSeq_source>mitochondrion Bos taurus (cattle)</GBSeq_source>
  <GBSeq_organism>Bos taurus</GBSeq_organism>
  <GBSeq_taxonomy>Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Euteleostomi; Mammalia; Eutheria; Laurasiatheria; Cetartiodactyla; Ruminantia; Pecora; Bovidae; Bovinae; Bos</GBSeq_taxonomy>
  <GBSeq_references>
    <GBReference>
      <GBReference_reference>1</GBReference_reference>
      <GBReference_position>1..906</GBReference_position>
      <GBReference_authors>
        <GBAuthor>Ginja,C.</GBAuthor>
        <GBAuthor>Penedo,M.C.</GBAuthor>
        <GBAuthor>Melucci,L.</GBAuthor>
        <GBAuthor>Quiroz,J.</GBAuthor>
        <GBAuthor>Martinez Lopez,O.R.</GBAuthor>
        <GBAuthor>Revidatti,M.A.</GBAuthor>
        <GBAuthor>Martinez-Martinez,A.</GBAuthor>
        <GBAuthor>Delgado,J.V.</GBAuthor>
        <GBAuthor>Gama,L.T.</GBAuthor>
      </GBReference_authors>
      <GBReference_title>Origins and genetic diversity of New World Creole cattle: inferences from mitochondrial and Y chromosome polymorphisms</GBReference_title>
      <GBReference_journal>Anim. Genet. (2009) In press</GBReference_journal>
      <GBReference_xref>
        <GBXref>
          <GBXref_dbname>doi</GBXref_dbname>
          <GBXref_id>10.1111/j.1365-2052.2009.01976.x</GBXref_id>
        </GBXref>
      </GBReference_xref>
      <GBReference_pubmed>19817725</GBReference_pubmed>
      <GBReference_remark>Publication Status: Available-Online prior to print</GBReference_remark>
    </GBReference>
    <GBReference>
      <GBReference_reference>2</GBReference_reference>
      <GBReference_position>1..906</GBReference_position>
      <GBReference_authors>
        <GBAuthor>Ginja,C.</GBAuthor>
        <GBAuthor>Melucci,L.</GBAuthor>
        <GBAuthor>Quiroz,J.</GBAuthor>
        <GBAuthor>Martinez,R.</GBAuthor>
        <GBAuthor>Revidatti,M.A.</GBAuthor>
        <GBAuthor>Martinez-Martinez,A.</GBAuthor>
        <GBAuthor>Penedo,M.C.T.</GBAuthor>
        <GBAuthor>Gama,L.T.</GBAuthor>
      </GBReference_authors>
      <GBReference_title>Direct Submission</GBReference_title>
      <GBReference_journal>Submitted (10-MAR-2009) Veterinary Genetics Laboratory, University of California, One Shields Avenue, Davis, CA 95616, USA</GBReference_journal>
    </GBReference>
  </GBSeq_references>
  <GBSeq_feature-table>
    <GBFeature>
      <GBFeature_key>source</GBFeature_key>
      <GBFeature_location>1..906</GBFeature_location>
      <GBFeature_intervals>
        <GBInterval>
          <GBInterval_from>1</GBInterval_from>
          <GBInterval_to>906</GBInterval_to>
          <GBInterval_accession>FJ815864.1</GBInterval_accession>
        </GBInterval>
      </GBFeature_intervals>
      <GBFeature_quals>
        <GBQualifier>
          <GBQualifier_name>organism</GBQualifier_name>
          <GBQualifier_value>Bos taurus</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>organelle</GBQualifier_name>
          <GBQualifier_value>mitochondrion</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>mol_type</GBQualifier_name>
          <GBQualifier_value>genomic DNA</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>isolate</GBQualifier_name>
          <GBQualifier_value>FRI9133</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>db_xref</GBQualifier_name>
          <GBQualifier_value>taxon:9913</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>country</GBQualifier_name>
          <GBQualifier_value>Portugal</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>note</GBQualifier_name>
          <GBQualifier_value>breed: Friesian</GBQualifier_value>
        </GBQualifier>
      </GBFeature_quals>
    </GBFeature>
    <GBFeature>
      <GBFeature_key>D-loop</GBFeature_key>
      <GBFeature_location>&lt;1..&gt;906</GBFeature_location>
      <GBFeature_intervals>
        <GBInterval>
          <GBInterval_from>1</GBInterval_from>
          <GBInterval_to>906</GBInterval_to>
          <GBInterval_accession>FJ815864.1</GBInterval_accession>
        </GBInterval>
      </GBFeature_intervals>
      <GBFeature_partial5 value="true"/>
      <GBFeature_partial3 value="true"/>
    </GBFeature>
  </GBSeq_feature-table>
  <GBSeq_sequence>acactattaatatagttccataaatacaaagagccttatcagtattaaatttatcaaaaatcccaataactcaacacagaatttgcaccctaaccaaatattacaaacaccactagctaacataacacgcccatacacagaccacagaatgaattacctacgcaaggggtaatgtacataacattaatgtaataaagacataatatgtatatagtacattaaattatatgccccatgcatataagcaagtacatgacctctatagcagtacataatacatataattattgactgtacatagtacattatgtcaaattcattcttgatagtatatctatatattccttaccattagatcacgagcttaattaccatgccgcgtgaaaccagcaacccgctaggcagggatccctcttctcgctccgggcccataaaccgtgggggtcgctatccaatgaattttaccaggcatctggttctttcttcagggccatctcatctaaaacggtccattctttcctcttaaataagacatctcgatggactaatggctaatcagcccatgctcacacataactgtgctgtcatacatttggtatttttttattttgggggatgcttggactcagctatggccgtcaaaggccctgacccggagcatctattgtagctggacttaactgcatcttgagcaccagcataatgataagcgtggacatcacagtcaatggtcacaggacataaattatattatatatccccccttcataaaaatttcccccttaaatatctaccaccacttttaacagacttttccctagatacttatttaaatttttcacgctttcaatactcaatttagcactccaaacaaagtcaatatataaacgcagggccccccccccc</GBSeq_sequence>
</GBSeq>

<GBSeq>
  <GBSeq_locus>FJ815639</GBSeq_locus>
  <GBSeq_length>907</GBSeq_length>
  <GBSeq_strandedness>double</GBSeq_strandedness>
  <GBSeq_moltype>DNA</GBSeq_moltype>
  <GBSeq_topology>linear</GBSeq_topology>
  <GBSeq_division>MAM</GBSeq_division>
  <GBSeq_update-date>12-MAR-2010</GBSeq_update-date>
  <GBSeq_create-date>24-AUG-2009</GBSeq_create-date>
  <GBSeq_definition>Bos taurus isolate RG8076 D-loop, partial sequence; mitochondrial</GBSeq_definition>
  <GBSeq_primary-accession>FJ815639</GBSeq_primary-accession>
  <GBSeq_accession-version>FJ815639.1</GBSeq_accession-version>
  <GBSeq_other-seqids>
    <GBSeqid>gb|FJ815639.1|</GBSeqid>
    <GBSeqid>gi|256041383</GBSeqid>
  </GBSeq_other-seqids>
  <GBSeq_source>mitochondrion Bos taurus (cattle)</GBSeq_source>
  <GBSeq_organism>Bos taurus</GBSeq_organism>
  <GBSeq_taxonomy>Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Euteleostomi; Mammalia; Eutheria; Laurasiatheria; Cetartiodactyla; Ruminantia; Pecora; Bovidae; Bovinae; Bos</GBSeq_taxonomy>
  <GBSeq_references>
    <GBReference>
      <GBReference_reference>1</GBReference_reference>
      <GBReference_position>1..907</GBReference_position>
      <GBReference_authors>
        <GBAuthor>Ginja,C.</GBAuthor>
        <GBAuthor>Penedo,M.C.</GBAuthor>
        <GBAuthor>Melucci,L.</GBAuthor>
        <GBAuthor>Quiroz,J.</GBAuthor>
        <GBAuthor>Martinez Lopez,O.R.</GBAuthor>
        <GBAuthor>Revidatti,M.A.</GBAuthor>
        <GBAuthor>Martinez-Martinez,A.</GBAuthor>
        <GBAuthor>Delgado,J.V.</GBAuthor>
        <GBAuthor>Gama,L.T.</GBAuthor>
      </GBReference_authors>
      <GBReference_title>Origins and genetic diversity of New World Creole cattle: inferences from mitochondrial and Y chromosome polymorphisms</GBReference_title>
      <GBReference_journal>Anim. Genet. (2009) In press</GBReference_journal>
      <GBReference_xref>
        <GBXref>
          <GBXref_dbname>doi</GBXref_dbname>
          <GBXref_id>10.1111/j.1365-2052.2009.01976.x</GBXref_id>
        </GBXref>
      </GBReference_xref>
      <GBReference_pubmed>19817725</GBReference_pubmed>
      <GBReference_remark>Publication Status: Available-Online prior to print</GBReference_remark>
    </GBReference>
    <GBReference>
      <GBReference_reference>2</GBReference_reference>
      <GBReference_position>1..907</GBReference_position>
      <GBReference_authors>
        <GBAuthor>Ginja,C.</GBAuthor>
        <GBAuthor>Melucci,L.</GBAuthor>
        <GBAuthor>Quiroz,J.</GBAuthor>
        <GBAuthor>Martinez,R.</GBAuthor>
        <GBAuthor>Revidatti,M.A.</GBAuthor>
        <GBAuthor>Martinez-Martinez,A.</GBAuthor>
        <GBAuthor>Penedo,M.C.T.</GBAuthor>
        <GBAuthor>Gama,L.T.</GBAuthor>
      </GBReference_authors>
      <GBReference_title>Direct Submission</GBReference_title>
      <GBReference_journal>Submitted (10-MAR-2009) Veterinary Genetics Laboratory, University of California, One Shields Avenue, Davis, CA 95616, USA</GBReference_journal>
    </GBReference>
  </GBSeq_references>
  <GBSeq_feature-table>
    <GBFeature>
      <GBFeature_key>source</GBFeature_key>
      <GBFeature_location>1..907</GBFeature_location>
      <GBFeature_intervals>
        <GBInterval>
          <GBInterval_from>1</GBInterval_from>
          <GBInterval_to>907</GBInterval_to>
          <GBInterval_accession>FJ815639.1</GBInterval_accession>
        </GBInterval>
      </GBFeature_intervals>
      <GBFeature_quals>
        <GBQualifier>
          <GBQualifier_name>organism</GBQualifier_name>
          <GBQualifier_value>Bos taurus</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>organelle</GBQualifier_name>
          <GBQualifier_value>mitochondrion</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>mol_type</GBQualifier_name>
          <GBQualifier_value>genomic DNA</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>isolate</GBQualifier_name>
          <GBQualifier_value>RG8076</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>db_xref</GBQualifier_name>
          <GBQualifier_value>taxon:9913</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>country</GBQualifier_name>
          <GBQualifier_value>Portugal</GBQualifier_value>
        </GBQualifier>
        <GBQualifier>
          <GBQualifier_name>note</GBQualifier_name>
          <GBQualifier_value>breed: Ramo Grande</GBQualifier_value>
        </GBQualifier>
      </GBFeature_quals>
    </GBFeature>
    <GBFeature>
      <GBFeature_key>D-loop</GBFeature_key>
      <GBFeature_location>&lt;1..&gt;907</GBFeature_location>
      <GBFeature_intervals>
        <GBInterval>
          <GBInterval_from>1</GBInterval_from>
          <GBInterval_to>907</GBInterval_to>
          <GBInterval_accession>FJ815639.1</GBInterval_accession>
        </GBInterval>
      </GBFeature_intervals>
      <GBFeature_partial5 value="true"/>
      <GBFeature_partial3 value="true"/>
    </GBFeature>
  </GBSeq_feature-table>
  <GBSeq_sequence>acactattaatatagttccataaatacaaagagccttatcagtattaaatttatcaaaaatcccaataactcaacacagaatttgcaccctaaccaaatattacaaacaccactagctaacataacacgcccatacacagaccacagaatgaattacctacgcaaggggtaatgtacataacattaatgtaataaagacataatatgtatatagtacattaaattatatgccccatgcatataagcaagtacatgacctctatagcagtacataatacatataattattgactgtacatagtacattatgtcaaattcattcttgatagtatatctatatattccttaccattagatcacgagcttaattaccatgccgcgtgaaaccagcaacccgctaggcagggatccctcttctcgctccgggcccataaaccgtgggggtcgctatccaatgaattttaccaggcatctggttctttcttcagggccatctcatctaaaacggtccattctttcctcttaaataagacatctcgatggactaatggctaatcagcccatgctcacacataactgtgctgtcatacatttggtatttttttattttgggggatgcttggactcagctatggccgtcaaaggccctgacccggagcatctattgtagctggacttaactgcatcttgagcaccagcataatgataagcgtggacattacagtcaatggtcacaggacataaattatattatatatcccccccttcataaaaatttcccccttaaatatctaccaccacttttaacagacttttccctagatacttatttaaatttttcacgctttcaatactcaatttagcactccaaacaaagtcaatatataaacgcagggccccccccccc</GBSeq_sequence>
</GBSeq>
</GBSet>'