versions
version13: spec
	<version: '1.3' imports: #('0.7-baseline' )>

	spec for: #'common' do: [
		spec blessing: #'stable'.
		spec description: 'version 1.3'.
		spec author: 'HernanMoralesDurand'.
		spec timestamp: '4/1/2017 03:32'.
		spec 
			project: 'CodeGenerator' with: '1.0';
			project: 'CommonUtils' with: '1.1';
			project: 'Grease' with: '1.2.7';
			project: 'INIFileSupport' with: '0.1-baseline';
			project: 'NeoCSV' with: '13';
			project: 'NumericalMethods' with: '1.1';
			project: 'OSProcess' with: '4.6.4';
			project: 'PetitParser' with: '2.0';
			project: 'ProcessWrapper' with: '1.2';
			project: 'ProjectFramework' with: '1.0';
			project: 'Roassal2' with: '1.44';
			project: 'StringExtensions' with: '1.1';
			project: 'XMLParser' with: '2.5.2';
			project: 'XMLPullParser' with: '1.0-baseline';
			project: 'XMLWriter' with: '2.7.5'.
		spec 
			package: #BioAffymetrix with: 'BioAffymetrix-HernanMoralesDurand.6';
			package: 'BioArlequin' with: 'BioArlequin-HernanMoralesDurand.46';
			package: 'BioBenchmarks' with: 'BioBenchmarks-HernanMoralesDurand.3';
			package: 'BioBlast' with: 'BioBlast-HernanMoralesDurand.121';
			package: 'BioBlastSamples' with: 'BioBlastSamples-HernanMoralesDurand.6';
			package: 'BioBlastTests' with: 'BioBlastTests-HernanMoralesDurand.44';
			package: 'BioClassifier' with: 'BioClassifier-HernanMoralesDurand.64';
			package: 'BioClassifierTests' with: 'BioClassifierTests-HernanMoralesDurand.7';
			package: 'BioEBI' with: 'BioEBI-HernanMoralesDurand.2';
			package: 'BioEntrez' with: 'BioEntrez-HernanMoralesDurand.50';
			package: 'BioEntrezTests' with: 'BioEntrezTests-HernanMoralesDurand.15';
			package: 'BioFormatterTests' with: 'BioFormatterTests-HernanMoralesDurand.21';
			package: 'BioFormatters' with: 'BioFormatters-HernanMoralesDurand.103';
			package: 'BioHaplotypes' with: 'BioHaplotypes-HernanMoralesDurand.4';
			package: 'BioIllumina' with: 'BioIllumina-HernanMoralesDurand.5';
			package: #BioLAMPLD with: 'BioLAMPLD-HernanMoralesDurand.44';
			package: 'BioNCBI' with: 'BioNCBI-HernanMoralesDurand.20';
			package: 'BioNCBITests' with: 'BioNCBITests-hfm.3';
			package: 'BioParserTests' with: 'BioParserTests-HernanMoralesDurand.17';
			package: 'BioParsers' with: 'BioParsers-HernanMoralesDurand.103';
			package: #BioPharo4 with: 'BioPharo4-HernanMoralesDurand.17';
			package: 'BioPopulation' with: 'BioPopulation-HernanMoralesDurand.73';
			package: 'BioProject' with: 'BioProject-HernanMoralesDurand.36';
			package: 'BioProjectTests' with: 'BioProjectTests-HernanMoralesDurand.9';
			package: 'BioSoftwareCatalog' with: 'BioSoftwareCatalog-HernanMoralesDurand.7';
			package: 'BioSupport' with: 'BioSupport-HernanMoralesDurand.32';
			package: 'BioTools' with: 'BioTools-HernanMoralesDurand.220';
			package: 'BioToolsSamples' with: 'BioToolsSamples-HernanMoralesDurand.13';
			package: 'BioToolsTests' with: 'BioToolsTests-HernanMoralesDurand.38';
			package: 'BioWrapperTests' with: 'BioWrapperTests-hfm.4';
			package: 'BioWrappers' with: 'BioWrappers-HernanMoralesDurand.58'. ].
