accessing
parserNodes
	" See superimplementor's comment "

	^ #(
	'GBSeq_locus'
	'GBSeq_length'
	'GBSeq_strandedness'
	'GBSeq_moltype'
	'GBSeq_topology'
	'GBSeq_division'
	'GBSeq_update-date'
	'GBSeq_definition'	
	'GBSeq_accession-version'
	'GBSeq_source'
	'GBSeq_organism'
	'GBSeq_taxonomy'
	'GBReference_position'
	'GBReference_reference'
	'GBSeq_sequence'
	'GBAuthor'
	'GBReference_title'
	'GBReference_journal'
	)