accessing
eResults01
	" Private - Sample ESearch Output 01 "
	^ '<?xml version="1.0" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD eSearchResult, 11 May 2002//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSearch_020511.dtd">
<eSearchResult><Count>1</Count><RetMax>1</RetMax><RetStart>0</RetStart><QueryKey>1</QueryKey><WebEnv>NCID_1_55968937_130.14.18.46_9001_1286909754_2028035256</WebEnv><IdList>
		<Id>115304323</Id>
	</IdList><TranslationSet/><QueryTranslation>AF288373.2</QueryTranslation></eSearchResult>'