accessing
featureVectors01

	^ '>gi|198282148|ref|NC_011206.1| Acidithiobacillus ferrooxidans ATCC 53993 chromosome, complete genome
>gi|295691862|ref|NC_014106.1| Lactobacillus crispatus ST1, complete genome
>gi|224372070|ref|NC_012115.1| Nautilia profundicola AmH chromosome, complete genome
>gi|296051576|ref|NC_014149.1| Planctomyces limnophilus DSM 3776 plasmid pPLIM01, complete sequence
>gi|296120274|ref|NC_014148.1| Planctomyces limnophilus DSM 3776 chromosome, complete genome
>gi|91791058|ref|NC_007950.1| Polaromonas sp. JS666 plasmid 2, complete sequence
>gi|91790731|ref|NC_007949.1| Polaromonas sp. JS666 plasmid 1, complete sequence
>gi|91785913|ref|NC_007948.1| Polaromonas sp. JS666, complete genome
>gi|121602919|ref|NC_008781.1| Polaromonas naphthalenivorans CJ2, complete genome
>gi|121583582|ref|NC_008764.1| Polaromonas naphthalenivorans CJ2 plasmid pPNAP08, complete sequence
>gi|121583564|ref|NC_008763.1| Polaromonas naphthalenivorans CJ2 plasmid pPNAP07, complete sequence
>gi|121583543|ref|NC_008762.1| Polaromonas naphthalenivorans CJ2 plasmid pPNAP06, complete sequence
>gi|121583484|ref|NC_008761.1| Polaromonas naphthalenivorans CJ2 plasmid pPNAP05, complete sequence
>gi|121583343|ref|NC_008760.1| Polaromonas naphthalenivorans CJ2 plasmid pPNAP04, complete sequence
'