accessing
observations02

	^ { 'Japan:Shimane,Izumo,Koshi 3775' .
'Japan:Shimane,Izumo,Koshi 3775' .
'Japan:Shimane,Izumo,Koshi 3775' .
'Japan:Shimane,Oda,Kawai,Yoshinaga 60' .
'Japan:Shimane,Oda,Kawai,Yoshinaga 60' .
'Philippines:Cagbang,Oton,Iloilo' .
'Philippines:Ilocos Norte,Barangay,Pardan,Sarrat' .
'Philippines:Ilocos Norte,Barangay,Pariir,Sarrat' .
'Philippines:Ilocos Norte,Piddig' .
'Philippines:Ilocos Norte,Batac' .
'Japan:Shimane,Oda,Kawai,Yoshinaga 60' .
'Japan:Hokkaido,Otofuke,Namiki 8' .
'Japan:Hokkaido' .
'Japan:Shimane,Izumo,Koshi 3775' .
'China: Hubei Province' .
'China: Shanxi Province' .
'China: Sichuan Province' .
'China: Sichuan Province' .
'China: Gansu Province' .
'United Kingdom: Dudley Castle' .
'United Kingdom: Dudley Castle' .
'Japan:Shimane,Oda,Kawai,Yoshinaga 60' .
'Japan:Shimane,Kisuki' .
'Japan:Shimane,Kisuki' .
'Japan:Okayama,Asahimatchi-kita2272' .
'Japan:Hokkaido' }